gallery/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

maintheme/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'maintheme'
urlpatterns = [
    path('', views.maintheme_list, name='index'),
    path('contacts/', views.contacts, name='contacts'),
    path('news/', views.post, name='news'),
    path('gallery/', views.gallery, name='gallery'),
    path('about_us/', views.about_us, name='about_us'),
    
   
              ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mksglass/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('maintheme.urls')),
    path('admin/', admin.site.urls),
    # path('gallery/', include('gallery.urls')),
]

urls.py
# from django.contrib import admin
# from django.urls import include, path

# urlpatterns = [
#     path('polls/', include('polls.urls')),
#     path('admin/', admin.site.urls),
# ]

gallery/models.py
from django.db import models

# Create your models here.

maintheme/models.py
#my changes all
from django.contrib.sites.models import Site#my
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='автор')
    title = models.CharField(max_length=200, verbose_name='название поста')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now, verbose_name='дата создания')
    published_date = models.DateTimeField(blank=True, null=True, verbose_name='дата убликации')
    img = models.ImageField(upload_to='media/img/', 
                       verbose_name='Грузи епт', null = True, blank = True)
                       

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
    

class Photo(models.Model):
    photo_text = models.CharField(max_length=35, verbose_name='название')
    pub_date = models.DateTimeField('Дата публикации')
    img = models.ImageField(upload_to='media/img/gallery/',
                       verbose_name='Загрузка фото', null = True, blank = True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,
                               related_name='photo_posts', verbose_name='автор')
    def __str__(self):
        return self.photo_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
class PhotoFrameless(models.Model):
    PhotoFrameless_text = models.CharField(max_length=35, verbose_name='название')
    pub_date = models.DateTimeField('Дата публикации')
    img = models.ImageField(upload_to='media/img/gallery/',
                       verbose_name='Загрузка фото', null = True, blank = True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,
                               related_name='frameless_posts', verbose_name='автор')
    def __str__(self):
        return self.PhotoFrameless_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
class Gate(models.Model):
    gate_text = models.CharField(max_length=35, verbose_name='название')
    pub_date = models.DateTimeField('Дата публикации')
    img = models.ImageField(upload_to='media/img/gallery/',
                       verbose_name='Загрузка фото', null = True, blank = True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,
                               related_name='blog_posts', verbose_name='автор')
    def __str__(self):
        return self.gate_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
class Pvc(models.Model):
    Pvc_text = models.CharField(max_length=35, verbose_name='название')
    pub_date = models.DateTimeField('Дата публикации')
    img = models.ImageField(upload_to='media/img/gallery/',
                       verbose_name='Загрузка фото', null = True, blank = True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,
                               related_name='pvc_posts', verbose_name='автор')
    def __str__(self):
        return self.Pvc_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
class Metall(models.Model):
    metall_text = models.CharField(max_length=35, verbose_name='название')
    pub_date = models.DateTimeField('Дата публикации')
    img = models.ImageField(upload_to='media/img/gallery/',
                       verbose_name='Загрузка фото', null = True, blank = True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,
                               related_name='metall_posts', verbose_name='автор')
    def __str__(self):
        return self.metall_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

# class Photo1(models.Model):
#     photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
#     photo1_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)
#     def __str__(self):
#         return self.photo1_text

class Person(models.Model):
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    phone = models.CharField(max_length=15)
    about = models.CharField(max_length=200)


#for news
# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date = models.DateTimeField('date published')
# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)

# class Post(models.Model):
#     author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     title = models.CharField(max_length=200)
#     text = models.TextField()
#     created_date = models.DateTimeField(default=timezone.now)
#     published_date = models.DateTimeField(blank=True, null=True)

#     def publish(self):
#         self.published_date = timezone.now()
#         self.save()

#     def __str__(self):
#         return self.title

gallery/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse("Раздел в стадии разработки")
# Create your views here.

maintheme/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Post
from django.utils import timezone


from .models import Post, Photo, PhotoFrameless, Gate, Pvc, Metall

def maintheme_list(request):
    return render(request, 'maintheme/index.html', {})
def contacts(request):
    return render(request, 'maintheme/contacts.html', {})
def post(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'maintheme/news.html', {'posts': posts})
def gallery(request):
    photos = Photo.objects
    photoframeless = PhotoFrameless.objects
    gates = Gate.objects
    pvcs = Pvc.objects
    metalls = Metall.objects
    return render(request, 'maintheme/gallery.html', {'photos': photos, 'photoframeless' : photoframeless,
                                                      'gates': gates, 'pvcs': pvcs, 'metalls': metalls})
def about_us(request):
    return render(request, 'maintheme/about_us.html')

maintheme/templates/base.html
{% load static %}


<!DOCTYPE html>
<html>
<head>
    <title>MKS-GLASS</title>
    <meta charset="UTF-8">
    <link href="{% static "maintheme/style.css" %}" rel="stylesheet">
    <meta name="viewport" content="лофт перегородки, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="style.css">
    <script src="https://kit.fontawesome.com/d907e42274.js" crossorigin="anonymous"></script>

    
</head>

<body>
    <header>
        <nav>
            <input type="checkbox" id="checkbox-menu">
            <label for="checkbox-menu">
                <ul class="menu touch">
                    <li><a class="logo" href="#">M.K.S</a></li>
                    <li><a href="{% url 'maintheme:index' %}">Главная</a></li>
                    <li><a href="{% url 'maintheme:gallery' %}">Портфолио</a></li>
                    <li><a href="{% url 'maintheme:news' %}">Новости</a></li>
                    <li><a href="{% url 'maintheme:contacts' %}">Контакты</a></li>
                    <li><a href="{% url 'maintheme:about_us' %}">О нас</a></li>
                    
                </ul>
                <span class="toggle">☰</span>
            </label>
        </nav>
    </header>
    <main>
        <section class="intro wrapper">
            <div class="intro-img">
                <p class="intro-text">Проектирование,<br>
                    производство и<br>
                    установка изделий<br>
                     из алюминия и стали.</p>
            </div>
            <div class="intro-contacts">
                <p><i class="fas fa-phone-alt"></i>7(952)1021221</p>
                <p><i class="fas fa-map-marker-alt"></i>г. Воронеж</p>
            </div>
            
        </section>
    </main>

 <div id="date">
 {% block content %}{% endblock %}
 </div>

</body>
</html>

maintheme/templates/maintheme/about_us.html
{% extends "base.html" %}

{% block content %}
<body>
    <main>
        
        <section class="stats wrapper">
            <div class="stats-text">
                <h2>Услуги нашей <br>компании</h2>
                <p>Мы специализируемся на изготовлении алюминиевых конструкций (холодное и тёплое остекление),
                    Loft перегородки, безрамное остекление из триплекса и калёного стекла любой сложности.
                    Наша компания имеет собственное производство, за счет этого заказы выполняются в короткие сроки.
                    Мы делаем качественную продукцию и даем на нее гарантию.
                    Компания "М.К.С." - это современное дизайнерское решение.
                    В сжатые сроки мы осуществим любые ваши пожелания и создадим конструкцию вашей мечты.</p>
            </div>
        </section>
    </main>
</body>
{% endblock %}

maintheme/templates/maintheme/base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>MKS-GLASS</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="{% static "maintheme/style.css" %}" rel="stylesheet">
    <meta name="viewport" http-equiv="Content-Type" content="width=device-width, initial-scale=1.0" charset="utf-8">
    <meta name="description" content="лофт перегородки">
    <p>г. Воронеж.<br>
    &#9990; тел.: +7 (952) 102 12 21, +7 (905) 050 65 31. <br>
    &#9993; mks-glass@mail.ru<br>
    <a href="https://www.instagram.com/m.k.s.glass/">instagram</a><a href="https://vk.com/mks.glass">, vk</a><br>
    <h1 id = head1>Проектирование, производство и установка перегородок из алюминия и стали.</h1>
</head>
<body>

<!-- MENU -->
<ul id="navbar">
    <li><a href="../">Главная</a></li>
    <li><a href="../gallery">Портфолио</a></li>
    <li><a href=".">Новости</a></li>
    <li><a href="../contacts">Контакты</a></li>
    <li><a href="#">О нас</a></li>

</ul>

 <div id="date">
 {% block content %}{% endblock %}
 </div>

</body>
</html>

maintheme/templates/maintheme/contacts.html
{% extends "base.html" %}

{% block content %}

<div class="main">   
        <p class="h1-text">Записаться на замер или получить консультацию вы можете по телефонам:
        </p>
        <p><i class="fas fa-phone-alt"></i>+7 (952) 102 12 21 - Борис</p>
        <p><i class="fas fa-phone-alt"></i>+7 (905) 050 65 31 - Александр</p>
        <p><i class="fas fa-map-marker-alt"></i>г. Воронеж, Большая манежная д.13в.</p>
        <p><i class="far fa-envelope"></i>mks-glass@mail.ru</p>
        <a href="https://www.instagram.com/metallmaster36/"><i class="fab fa-instagram"></i>instagram</a><br>
        <a href="https://vk.com/mks.glass"><i class="fab fa-vk"></i>vk</a><br>
        <a href="https://www.facebook.com/groups/2522001238128747/"><i class="fab fa-facebook"></i>facebook</a><br></p>
    </div>

{% endblock %}

maintheme/templates/maintheme/forus.html
{% extends "base.html" %}

{% block content %}

<div class="main">   
        <p class="h1-text">Записаться на замер или получить консультацию вы можете по телефонам:
        </p>
        <p><i class="fas fa-phone-alt"></i>+7 (952) 102 12 21 - Борис</p>
        <p><i class="fas fa-phone-alt"></i>+7 (905) 050 65 31 - Александр</p>
        <p><i class="fas fa-map-marker-alt"></i>г. Воронеж, Большая манежная д.13в.</p>
        <p><i class="far fa-envelope"></i>mks-glass@mail.ru</p>
        <a href="https://www.instagram.com/m.k.s.glass/"><i class="fab fa-instagram"></i>instagram</a><br>
        <a href="https://vk.com/mks.glass"><i class="fab fa-vk"></i>vk</a><br>
        <a href="https://www.facebook.com/groups/2522001238128747/"><i class="fab fa-facebook"></i>facebook</a><br></p>
    </div>

{% endblock %}

maintheme/templates/maintheme/gallery.html
{% extends "base.html" %}

{% block content %}

        
        <div class="main"> 
            <p class="h1-text">Осекление таррас из алюминия и ПВХ</p>  
        <ul id="gallery">
                {% for photo in photos.reverse %}
                <li> {{ photo.photo_text}}<br>
                    <img src="{{ photo.img.url }}">
                </li>
                {% endfor %}  
            </ul>
        </div>
        
        <div class="main">
            <p class="h1-text">Безрамное остекление, стеклянные ограждения</p>
            <ul id="gallery">
                {% for photoframeless in photoframeless.reverse %}
                <li> {{ photoframeless.PhotoFrameless_text}}<br>
                    <img src="{{ photoframeless.img.url }}">
                </li>
                {% endfor %}  
            </ul>
        </div>
        <div class="main">
            <p class="h1-text">Въездные ворота, калитки, автоматика</p>
            <ul id="gallery">
                {% for x in gates.reverse %}
                <li> {{ x.gate_text}}<br>
                    <img src="{{ x.img.url }}">
                </li>
                {% endfor %}  
            </ul>
        </div>
        <div class="main">
            <p class="h1-text">Окна ПВХ, входные группы лоджии</p>
            <ul id="gallery">
                {% for d in pvcs.reverse %}
                <li> {{ d.Pvc_text}}<br>
                    <img src="{{ d.img.url }}">
                </li>
                {% endfor %}  
            </ul>
        </div>
        <div class="main">
            <p class="h1-text">Металлоконструкции, лестницы, стеллажи</p>
            <ul id="gallery">
                {% for c in metalls.reverse %}
                <li> {{ c.metall_text}}<br>
                    <img src="{{ c.img.url }}"> 
                    <!-- height="300" width="300"-->
                </li>
                {% endfor %}  
            </ul>
        </div>
{% endblock %}

maintheme/templates/maintheme/gallery2.html
{% extends "base.html" %}

{% block content %}

        
        <div class="main"> 
            <p class="h1-text">Осекление таррас из алюминия и ПВХ</p>  
        <ul id="gallery">
                {% for photo in photos.reverse %}
                <li> {{ photo.photo_text}}<br>
                    <img src="{{ photo.img.url }}">
                </li>
                {% endfor %}  
            </ul>
        </div>
        
        <div class="main">
            <p class="h1-text">Безрамное остекление, стеклянные ограждения</p>
            <ul id="gallery">
                {% for photoframeless in photoframeless.reverse %}
                <li> {{ photoframeless.PhotoFrameless_text}}<br>
                    <img src="{{ photoframeless.img.url }}">
                </li>
                {% endfor %}  
            </ul>
        </div>
        <div class="main">
            <p class="h1-text">Въездные ворота, калитки, автоматика</p>
            <ul id="gallery">
                {% for x in gates.reverse %}
                <li> {{ x.gate_text}}<br>
                    <img src="{{ x.img.url }}">
                </li>
                {% endfor %}  
            </ul>
        </div>
        <div class="main">
            <p class="h1-text">Окна ПВХ, входные группы лоджии</p>
            <ul id="gallery">
                {% for d in pvcs.reverse %}
                <li> {{ d.Pvc_text}}<br>
                    <img src="{{ d.img.url }}">
                </li>
                {% endfor %}  
            </ul>
        </div>
        <div class="main">
            <p class="h1-text">Металлоконструкции, лестницы, стеллажи</p>
            <ul id="gallery">
                {% for c in metalls.reverse %}
                <li> {{ c.metall_text}}<br>
                    <img src="{{ c.img.url }}"> 
                    <!-- height="300" width="300"-->
                </li>
                {% endfor %}  
            </ul>
        </div>
{% endblock %}

maintheme/templates/maintheme/index.html
{% extends "base.html" %}

{% block content %}

<div class="main">

            <p class="h1-text">Перегородки в стиле Loft<br>
            <p class="main">
            
            <img class="main-img" src="/media/loft03.jpg">
                
                Проектирование, изготовление и установка loft перегородок.<br>
                Материал для перегородок - сталь. Материал перегородок для<br>
                ванных комнат и душевых - нержавеющая сталь.<br>
                Покрытие - порошковая покраска по каталогу RAL(матовая, глянец, муар) или лак.<br>
                Двери с нажимными гарнитурами или офисными ручками.<br>
                Заполнение - стекло на выбор или триплекс.<br>
                Любые нестандартные решения распашные, раздвижные, стационарные.<br>
            </p>
            <p class="h1-text">Остекление террас и беседок</p>
            <p class="main">
                <img class="main-img" src="/media/terrass.png">
                
                Остекление террас и беседок является замечательным вариантом 
                защиты людей от неблагоприятных погодных условий, а также 
                проведения приятного вечера на природе, обеспечивающей ощущение 
                свободы, в тепле и комфорте<br>
                Варианты остекления: Теплый или холодный.<br>
                Материалы: ПВХ, Алюминий, Сталь, Безрамное Остекление.<br>
                <br><br><br>
            </p>
            <p class="h1-text">Перегородки</p>
            <p class="main">
                <img class="main-img" src="/media/ALT111.png">
                
                Изгатавливаем офисные и домашние перегородки из Алюминия пвх и стали 
                и закаленного стекла, возможно изготовление перегородок со встроенными 
                жалюзями. Подберем оптимальный вариант по желанию заказчика и возможностям 
                помещения. <br><br>
                <br><br><br><br><br><br>
                </p>
            <p class="h1-text">Воротные и роллетные системы и автоматика.</p>
            <p  class="main">
                <img class="main-img" src="/media/gates1.png">
                Откатные, секционные и распашные ворота, рольставни.<br>
                Автоматическое и ручное упраление.<br>
                Возможность подключения к системе "Умный дом"<br>
                В работе используем Ворота компании Alutech и Стальные ворота собственного
                производства, с различными вариантами отделки.<br>
                <br><br><br><br><br><br>
            </p>
            <!-- <li>Пункт 5</li>
            <li>Пункт 6</li>
            <li>Пункт 7</li>
            <li>Пункт 8</li> -->
    </ul>
    </div>
    <div>
    <p class="main"> 
            &bull; собственное производство конструкций<br>
            &bull; большой опыт работы с уникальными проектами<br>
            &bull; проектирование и применение нестандартных решений<br>
            &bull; внимательное отношение к деталям и мелочам<br>
            &bull; Клиенториентированность. Индивидуальный подход к каждому заказу<br>
            &bull; команда профессионалов с большим опытом работы
        </p>
    </div> 
{% endblock %}

maintheme/templates/maintheme/news.html
{% extends "base.html" %}


{% block content %}


<!-- <ul id="navbar">
  <li><a href="{% url 'maintheme:index' %}">Главная</a></li>
  <li><a href="{% url 'maintheme:gallery' %}">Портфолио</a></li>
  <li><a href="{% url 'maintheme:news' %}">Новости</a></li>
  <li><a href="{% url 'maintheme:contacts' %}">Контакты</a></li>
  <li><a href="{% url 'maintheme:index' %}">О нас</a></li>

</ul> -->

    
{% for post in posts.reverse %}

<div class="wrapperer">

  <div class="item">
    <p></p>опубликовано: {{ post.published_date }}</p>
  
    <!-- {{ article.title }} -->  
    <p class="h1-text">{{ post.title }}</p>
  
    <p  class="main">  <img class="main-img" src="{{ post.img.url }}">{{ post.text|linebreaksbr }}</p>
  </div>
  </div>   
{% endfor %}    

{% endblock %}

maintheme/templates/maintheme/news1.html
{% extends "base.html" %}


{% block content %}
<!-- {% load staticfiles %}
{% load static %} -->
<ul id="navbar">
  <li><a href="../">Главная</a></li>
  <li><a href="../gallery">Портфолио</a></li>
  <li><a href=".">Новости</a></li>
  <li><a href="../contacts">Контакты</a></li>
  <li><a href="#">О нас</a></li>

</ul>

    
{% for post in posts.reverse %}
  <div class="date">
    <p class="info">опубликовано: {{ post.published_date }}</p>
  </div>
    <!-- {{ article.title }} -->  
    <h1><a href="">{{ post.title }}</a></h1>
  <div>
    <p id='news'>
      <img src="{{ post.img.url }}">
      {{ post.text|linebreaksbr }}
    </p>
  </div>   
{% endfor %}    

{% endblock %}

maintheme/templates/news.html
{% extends "maintheme/base.html" %}

{% block content %}
<!-- {% load staticfiles %}
{% load static %} -->


    
{% for post in posts.reverse %}
  <div class="date">
    <p class="info">опубликовано: {{ post.published_date }}</p>
  </div>
    <!-- {{ article.title }} -->  
    <h1><a href="">{{ post.title }}</a></h1>
  <div>
    <p id='news'>
      <img src="{{ post.img.url }}">
      {{ post.text|linebreaksbr }}
    </p>
  </div>   
{% endfor %}    

{% endblock %}